<?php

namespace PillsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategory($category)
    {

        $qb = $this->getEntityManager()->createQueryBuilder('c');

        $qb
            ->select('c')
            ->from('PillsBundle:Category', 'c')
            ->where('c.title = :title')
            ->setParameter('title', $category)
            ->getQuery();
        $query = $qb->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
