<?php

namespace PillsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Cities
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cities extends EntityRepository
{
}
