<?php

namespace PillsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends EntityRepository
{
    public function getRatingByPost($post)
    {
        $qb = $this->getEntityManager()->createQueryBuilder('r');

        $qb
            ->select('r')
            ->from('PillsBundle:Rating', 'r')
            ->where('r.post = :post')
            ->setParameter('post', $post)
            ->getQuery();

        $query = $qb->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
