<?php

namespace PillsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{

    public function findTopTags()
    {
        $tags = $this->getEntityManager()->getRepository('PillsBundle:Tag')
            ->createQueryBuilder('t')
            ->groupBy('t.hashTag')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult();

        usort($tags, function ($a, $b) {
            if (COUNT($a->getPost()) == COUNT($b->getPost())) {
                return 0;
            }

            return (COUNT($a->getPost()) > COUNT($b->getPost())) ? -1 : 1;
        });

        return $tags;
    }

    public function getTag($hash)
    {

        $qb = $this->getEntityManager()->createQueryBuilder('t');

        $qb
            ->select('t')
            ->from('PillsBundle:Tag', 't')
            ->where('t.hashTag = :hash')
            ->setParameter('hash', $hash)
            ->getQuery();
        $query = $qb->getQuery();
        $results = $query->getResult();

        return $results;
    }

    public function getPostByCategory($hash)
    {

        $qb = $this->getEntityManager()->createQueryBuilder('t');

        $qb
            ->select('t')
            ->from('PillsBundle:Post', 't')
            ->where('t. = :hash')
            ->setParameter('hash', $hash)
            ->getQuery();
        $query = $qb->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
