<?php

namespace PillsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends EntityRepository
{
    public function getType($slug)
    {

        $qb = $this->getEntityManager()->createQueryBuilder('t');

        $qb
            ->select('t')
            ->from('PillsBundle:Type', 't')
            ->where('t.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery();
        $query = $qb->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
